/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop_.$slug'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop_/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/payment': typeof PaymentRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/treatments': typeof TreatmentsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/payment': typeof PaymentRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/treatments': typeof TreatmentsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/payment': typeof PaymentRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/treatments': typeof TreatmentsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/shop_/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/payment'
    | '/services'
    | '/shop'
    | '/treatments'
    | '/blog/$slug'
    | '/category/$slug'
    | '/conditions/$slug'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/payment'
    | '/services'
    | '/shop'
    | '/treatments'
    | '/blog/$slug'
    | '/category/$slug'
    | '/conditions/$slug'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/payment'
    | '/services'
    | '/shop'
    | '/treatments'
    | '/blog/$slug'
    | '/category/$slug'
    | '/conditions/$slug'
    | '/shop_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  PaymentRoute: typeof PaymentRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  TreatmentsRoute: typeof TreatmentsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop_/$slug': {
      id: '/shop_/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  PaymentRoute: PaymentRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  TreatmentsRoute: TreatmentsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
